services:
  - type: web
    name: gy-project-frontend
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: node server.cjs
    envVars:
      - key: VITE_API_URL
        value: /api
      - key: BACKEND_URL
        value: http://gyproject-env-1.eba-h3s8e4pe.us-east-1.elasticbeanstalk.com
